kind: StagedPolicySequence
apiVersion: api.ibm.com/v1
metadata:
  name: PolicySeq_SPGI_TEL_LL_Swagger_Petstore
  namespace: MyAPIs
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - webMethods
spec:
  routing:
    - $ref: MyAPIs:default-invoke-policy-PolicySeq_SPGI_TEL_LL_Swagger_Petstore:1.0
